/* ── NCERT-grounded lab specifications (data-driven 3D classification labs) ──
   Sources: NCERT Class 6 "Curiosity" (2024) & NCERT Class 8 Science.
   Each item carries a `shape` (3D model) + `color`; each lab a `mode` that
   drives the real-world test process (magnet test / dissolving in water /
   examining properties). Driven by genlab3d.jsx + labitems3d.jsx. */

export const GEN_LABS = {
  /* ───────── Class 6 · Chemistry — dissolve in water ───────── */
  solubility: {
    id: "solubility",
    title: "Soluble & Insoluble Substances",
    cls: "Class 6", subject: "Chemistry",
    chapter: "Methods of Separation of Substances (NCERT Curiosity)",
    icon: "beaker", accent: "#0d9488", mode: "water",
    aim: "To test whether different everyday substances are soluble or insoluble in water.",
    theory: "A substance that dissolves completely in water forms a clear solution and is soluble. One that does not dissolve and settles or floats is insoluble.",
    materials: ["Beaker of water", "Stirring rod", "Sugar", "Common salt", "Sand", "Chalk powder", "Copper sulphate", "Cooking oil"],
    testVerb: "Add to water & stir",
    categories: [
      { key: "soluble", label: "Soluble", color: "#0d9488", desc: "Dissolves fully — clear solution" },
      { key: "insoluble", label: "Insoluble", color: "#ea580c", desc: "Does not dissolve — stays visible" },
    ],
    items: [
      { id: "sugar", name: "Sugar", shape: "powder", color: "#ffffff", category: "soluble", fact: "The sugar disappears and the water stays clear — sugar is soluble in water." },
      { id: "salt", name: "Common Salt", shape: "powder", color: "#eef2f7", category: "soluble", fact: "The salt dissolves completely into a clear solution — salt is soluble." },
      { id: "coppersulphate", name: "Copper Sulphate", shape: "crystal", color: "#3b82f6", category: "soluble", fact: "It dissolves and turns the water blue — copper sulphate is soluble." },
      { id: "sand", name: "Sand", shape: "grains", color: "#c2a878", category: "insoluble", fact: "The sand settles at the bottom and the water stays murky — sand is insoluble." },
      { id: "chalk", name: "Chalk Powder", shape: "powder", color: "#e2e8f0", category: "insoluble", fact: "The chalk makes the water cloudy and settles down — chalk is insoluble." },
      { id: "oil", name: "Cooking Oil", shape: "liquid", color: "#f4d03f", category: "insoluble", fact: "The oil floats on top and won't mix — oil is insoluble in water." },
    ],
    question: {
      q: "Why does sugar seem to 'disappear' when stirred into water?",
      options: ["It dissolves — its particles spread evenly between the water particles", "It reacts with water and turns into a gas"],
      ans: 0,
      correctMsg: "Exactly! Soluble substances break into tiny particles that spread evenly among the water particles, forming a clear solution.",
      incorrectMsg: "Not quite — sugar doesn't turn into gas. It dissolves: its particles spread between the water particles. Try again!",
    },
    conclusion: "Sugar, salt and copper sulphate dissolve in water (soluble). Sand, chalk and oil do not dissolve (insoluble). Insoluble solids can later be separated by filtration.",
  },

  /* ───────── Class 6 · Physics — magnet test ───────── */
  magnetism: {
    id: "magnetism",
    title: "Magnetic & Non-Magnetic Materials",
    cls: "Class 6", subject: "Physics",
    chapter: "Ch 4 · Exploring Magnets (NCERT Curiosity)",
    icon: "atom", accent: "#4f46e5", mode: "magnet",
    aim: "To find which materials are attracted by a magnet (magnetic) and which are not (non-magnetic).",
    theory: "Materials attracted to a magnet are magnetic — iron, cobalt and nickel are magnetic. Materials not attracted are non-magnetic.",
    materials: ["Bar magnet", "Iron nail", "Steel pin", "Nickel coin", "Aluminium foil", "Copper wire", "Plastic scale"],
    testVerb: "Bring the magnet near",
    categories: [
      { key: "magnetic", label: "Magnetic", color: "#4f46e5", desc: "Jumps to the magnet" },
      { key: "nonmagnetic", label: "Non-magnetic", color: "#64748b", desc: "Not attracted" },
    ],
    items: [
      { id: "ironnail", name: "Iron Nail", shape: "nail", color: "#8a8f98", category: "magnetic", fact: "The nail jumps and sticks to the magnet — iron is magnetic!" },
      { id: "steelpin", name: "Steel Pin", shape: "pin", color: "#cbd5e1", category: "magnetic", fact: "The pin is pulled to the magnet — steel (mostly iron) is magnetic." },
      { id: "nickel", name: "Nickel Coin", shape: "coin", color: "#aeb4bd", category: "magnetic", fact: "It clings to the magnet — nickel is one of the few magnetic metals." },
      { id: "aluminium", name: "Aluminium Foil", shape: "foil", color: "#d4d8de", category: "nonmagnetic", fact: "Nothing happens — aluminium is non-magnetic." },
      { id: "copper", name: "Copper Wire", shape: "wire", color: "#b45309", category: "nonmagnetic", fact: "The magnet has no effect — copper is non-magnetic." },
      { id: "plastic", name: "Plastic Scale", shape: "ruler", color: "#60a5fa", category: "nonmagnetic", fact: "No attraction at all — plastic is non-magnetic." },
    ],
    question: {
      q: "Iron, cobalt and nickel are attracted to magnets. What do we call such materials?",
      options: ["Magnetic materials", "Conductors"],
      ans: 0,
      correctMsg: "Correct! Materials attracted by a magnet are called magnetic materials — iron, cobalt and nickel are the common ones.",
      incorrectMsg: "Not quite — conductors carry electricity. Materials attracted by a magnet are 'magnetic materials'. Try again!",
    },
    conclusion: "The iron nail, steel pin and nickel coin are attracted by the magnet (magnetic). Aluminium, copper and plastic are not attracted (non-magnetic).",
  },

  /* ───────── Class 6 · Chemistry — torch light test ───────── */
  "materials-light": {
    id: "materials-light",
    title: "Transparent, Translucent & Opaque",
    cls: "Class 6", subject: "Chemistry",
    chapter: "Ch 6 · Materials Around Us (NCERT Curiosity)",
    icon: "eye", accent: "#0284c7", mode: "light",
    aim: "To group materials by how much light passes through them — transparent, translucent or opaque.",
    theory: "Materials we can see through clearly are transparent. Materials we can see through only partially are translucent. Materials we cannot see through at all are opaque.",
    materials: ["Torch", "White screen", "Glass slab", "Glass of water", "Butter paper", "Frosted glass", "Wooden block", "Steel plate"],
    testVerb: "Shine the torch through",
    categories: [
      { key: "transparent", label: "Transparent", color: "#0284c7", desc: "Light passes fully — clear bright spot" },
      { key: "translucent", label: "Translucent", color: "#d97706", desc: "Some light passes — dim, fuzzy glow" },
      { key: "opaque", label: "Opaque", color: "#475569", desc: "No light passes — a shadow forms" },
    ],
    items: [
      { id: "glass", name: "Glass Slab", shape: "slab", color: "#dbeafe", category: "transparent", fact: "The beam passes straight through and makes a bright, sharp spot on the screen — glass is transparent." },
      { id: "water", name: "Glass of Water", shape: "cup", color: "#bfe3f0", category: "transparent", fact: "Light travels through the clear water and lights up the screen — water is transparent." },
      { id: "butter", name: "Butter Paper", shape: "sheet", color: "#fef9c3", category: "translucent", fact: "Only some light gets through, making a dim fuzzy glow — butter paper is translucent." },
      { id: "frosted", name: "Frosted Glass", shape: "frosted", color: "#cbd5e1", category: "translucent", fact: "The light scatters into a soft blur on the screen — frosted glass is translucent." },
      { id: "wood", name: "Wooden Block", shape: "block", color: "#92623a", category: "opaque", fact: "No light reaches the screen — only a dark shadow. Wood is opaque." },
      { id: "steel", name: "Steel Plate", shape: "panel", color: "#cbd5e1", category: "opaque", fact: "The metal blocks the beam completely and casts a shadow — steel is opaque." },
    ],
    question: {
      q: "Why can we see clearly through a glass slab but not through a wooden block?",
      options: ["Glass lets light pass through it; wood blocks light completely", "Glass is colder than wood"],
      ans: 0,
      correctMsg: "Exactly! Seeing through a material is about light passing through it — transparent materials let light through, opaque ones block it.",
      incorrectMsg: "Not quite — temperature has nothing to do with it. It's about whether light can pass through. Try again!",
    },
    conclusion: "Glass and water let light pass fully (transparent). Butter paper and frosted glass let some light through (translucent). Wood and steel block light completely (opaque).",
  },

  /* ───────── Class 6 · Chemistry — choose the separation method ───────── */
  separation: {
    id: "separation",
    title: "Methods of Separation",
    cls: "Class 6", subject: "Chemistry",
    chapter: "Ch 9 · Methods of Separation in Everyday Life (NCERT Curiosity)",
    icon: "beaker", accent: "#d97706", mode: "inspect",
    aim: "To choose the correct method for separating the components of everyday mixtures.",
    theory: "We pick a separation method using differences between the components: size or colour (handpicking), weight in moving air (winnowing), particle size with a mesh (sieving), or an insoluble solid in a liquid (filtration).",
    materials: ["Magnifier", "Mixture samples", "Sieve", "Filter paper & funnel", "Winnowing tray"],
    testVerb: "Inspect the mixture",
    categories: [
      { key: "handpicking", label: "Handpicking", color: "#0d9488", desc: "Few large, different-looking pieces" },
      { key: "winnowing", label: "Winnowing", color: "#0284c7", desc: "Lighter part blows away in wind" },
      { key: "sieving", label: "Sieving", color: "#7c3aed", desc: "Different particle sizes — use a mesh" },
      { key: "filtration", label: "Filtration", color: "#d97706", desc: "Insoluble solid in a liquid" },
    ],
    items: [
      { id: "stones", name: "Stones in Rice", shape: "mixture", color: "#f5f0e6", category: "handpicking", fact: "The stones are few, larger and look different from the rice — simply pick them out by hand." },
      { id: "husk", name: "Husk & Grain", shape: "mixture", color: "#d9b98a", category: "winnowing", fact: "Husk is much lighter than grain — wind carries the husk away while grain falls straight down. That is winnowing." },
      { id: "bran", name: "Bran in Flour", shape: "powder", color: "#efe3cd", category: "sieving", fact: "Fine flour falls through the mesh while the coarser bran stays behind — sieving separates by particle size." },
      { id: "tea", name: "Tea Leaves in Tea", shape: "specks", color: "#b4762d", category: "filtration", fact: "The liquid tea passes through a strainer while the insoluble leaves are caught — that's filtration." },
      { id: "sandwater", name: "Sand in Water", shape: "specks", color: "#9fb6c1", category: "filtration", fact: "Insoluble sand is trapped by filter paper while clear water passes through — filtration gives clean water." },
      { id: "pebbles", name: "Pebbles in Sand", shape: "mixture", color: "#d9c49a", category: "sieving", fact: "Sand slips through the sieve's holes while the larger pebbles stay on top — sieving works by size." },
    ],
    question: {
      q: "In winnowing, why does the husk separate from the grain?",
      options: ["Husk is lighter, so moving air carries it away", "Husk dissolves in the air"],
      ans: 0,
      correctMsg: "Correct! Winnowing works because the lighter husk is carried away by wind while heavier grains fall straight down.",
      incorrectMsg: "Not quite — nothing dissolves in air here. The husk is simply lighter, so the wind carries it away. Try again!",
    },
    conclusion: "Stones in rice are handpicked; husk is winnowed away from grain; bran and pebbles are sieved out by size; tea leaves and sand are removed from liquids by filtration.",
  },

  /* ───────── Class 6 · Physics — types of motion ───────── */
  motion: {
    id: "motion",
    title: "Types of Motion",
    cls: "Class 6", subject: "Physics",
    chapter: "Ch 5 · Measurement of Length and Motion (NCERT Curiosity)",
    icon: "refresh", accent: "#dc2626", mode: "motion",
    aim: "To observe moving objects and classify their motion as linear, circular or oscillatory.",
    theory: "Motion along a straight line is linear motion. Motion along a circular path is circular motion. To-and-fro motion about a fixed position is oscillatory motion.",
    materials: ["Toy car", "Rolling ball", "Table fan", "Spinning top", "Pendulum", "Swing model"],
    testVerb: "Tap to set it moving",
    categories: [
      { key: "linear", label: "Linear", color: "#0d9488", desc: "Straight-line motion" },
      { key: "circular", label: "Circular", color: "#7c3aed", desc: "Moves along a circle" },
      { key: "oscillatory", label: "Oscillatory", color: "#d97706", desc: "To-and-fro about a point" },
    ],
    items: [
      { id: "car", name: "Toy Car", shape: "car", color: "#dc2626", category: "linear", fact: "The car moves along a straight path on the bench — this is linear motion." },
      { id: "ball", name: "Rolling Ball", shape: "ball", color: "#f59e0b", category: "linear", fact: "The ball rolls along a straight line — its motion is linear (the ball itself also spins as it rolls!)." },
      { id: "fan", name: "Table Fan", shape: "fan", color: "#60a5fa", category: "circular", labelY: 0.62, fact: "Each blade moves round and round along a circle — the fan shows circular motion." },
      { id: "top", name: "Spinning Top", shape: "top", color: "#7c3aed", category: "circular", fact: "Every point of the top moves in a circle about its spike — circular (rotational) motion." },
      { id: "pendulum", name: "Pendulum", shape: "pendulum", color: "#d97706", category: "oscillatory", labelY: 0.68, fact: "The bob swings to and fro about its rest position — this is oscillatory motion." },
      { id: "swing", name: "Swing", shape: "swing", color: "#dc2626", category: "oscillatory", labelY: 0.62, fact: "The swing moves back and forth again and again — oscillatory motion, just like in a park." },
    ],
    question: {
      q: "A point marked on a moving fan blade traces a circle. What type of motion is this?",
      options: ["Circular motion", "Linear motion"],
      ans: 0,
      correctMsg: "Correct! Any point on the blade moves along a circular path around the centre — that's circular motion.",
      incorrectMsg: "Look again at the path — it goes round and round in a circle, not in a straight line. Try again!",
    },
    conclusion: "The toy car and rolling ball move in straight lines (linear motion). The fan blades and spinning top move along circles (circular motion). The pendulum and swing move to and fro (oscillatory motion).",
  },

  /* ───────── Class 6 · Physics — read the thermometer ───────── */
  temperature: {
    id: "temperature",
    title: "Temperature & Its Measurement",
    cls: "Class 6", subject: "Physics",
    chapter: "Ch 7 · Temperature and its Measurement (NCERT Curiosity)",
    icon: "drop", accent: "#0f766e", mode: "thermo",
    aim: "To measure the temperature of different water samples with a laboratory thermometer and classify them as cold, warm or hot.",
    theory: "Temperature is the measure of how hot or cold something is, measured with a thermometer in degrees Celsius (°C). Our sense of touch is unreliable — only a thermometer gives the true reading.",
    materials: ["Laboratory thermometer (−10 °C to 110 °C)", "Water samples in glasses"],
    testVerb: "Dip the thermometer",
    categories: [
      { key: "cold", label: "Cold (≤10°C)", color: "#2563eb", desc: "At or below 10 °C" },
      { key: "warm", label: "Warm (11–45°C)", color: "#0d9488", desc: "Between 11 and 45 °C" },
      { key: "hot", label: "Hot (>45°C)", color: "#dc2626", desc: "Above 45 °C" },
    ],
    items: [
      { id: "icewater", name: "Ice-Water Mix", shape: "cup", color: "#bfdbfe", category: "cold", temp: 0, fact: "The thermometer reads 0 degrees Celsius — melting ice and water stay at 0 °C. That's cold!" },
      { id: "chilled", name: "Chilled Lemonade", shape: "cup", color: "#fef08a", category: "cold", temp: 8, fact: "It reads 8 degrees Celsius — refrigerator-cold. Below 10 °C counts as cold." },
      { id: "tap", name: "Tap Water", shape: "cup", color: "#bae6fd", category: "warm", temp: 25, fact: "The mercury settles at 25 degrees Celsius — about room temperature. That's in the warm range." },
      { id: "body", name: "Body-Warm Water", shape: "cup", color: "#a7f3d0", category: "warm", temp: 37, fact: "It reads 37 degrees Celsius — the same as normal human body temperature." },
      { id: "milk", name: "Hot Milk", shape: "cup", color: "#fef3c7", category: "hot", temp: 60, fact: "The column rises to 60 degrees Celsius — too hot to sip quickly! Above 45 °C is hot." },
      { id: "boiling", name: "Boiling Water", shape: "cup", color: "#fecaca", category: "hot", temp: 100, fact: "The thermometer shoots up to 100 degrees Celsius — water boils at 100 °C at sea level." },
    ],
    question: {
      q: "A clinical thermometer reads only 35–42 °C. Why such a small range?",
      options: ["Because human body temperature stays within that range", "Because mercury freezes below 35 °C"],
      ans: 0,
      correctMsg: "Correct! A clinical thermometer is made only for body temperature, which stays near 37 °C — so its scale is just 35–42 °C.",
      incorrectMsg: "Not quite — mercury freezes far below that, at −39 °C. The range matches human body temperature. Try again!",
    },
    conclusion: "A laboratory thermometer measures each sample in °C: ice-water (0°) and chilled drinks are cold; tap water (25°) and body-warm water (37°) are warm; hot milk (60°) and boiling water (100°) are hot. Touch can deceive — the thermometer never does.",
  },

  /* ───────── Class 7 · Chemistry — physical vs chemical changes ───────── */
  changes: {
    id: "changes",
    title: "Physical & Chemical Changes",
    cls: "Class 7", subject: "Chemistry",
    chapter: "Ch 5 · Changes Around Us: Physical and Chemical (NCERT Curiosity)",
    icon: "refresh", accent: "#7c3aed", mode: "inspect",
    aim: "To examine everyday changes and classify them as physical or chemical changes.",
    theory: "In a physical change no new substance is formed — often only shape, size or state changes, and it can usually be reversed. In a chemical change a new substance with new properties is formed, and it usually cannot be reversed.",
    materials: ["Magnifier", "Ice cubes", "Paper", "Sugar & water", "Burnt paper ash", "Rusted iron nail", "Curd set from milk"],
    testVerb: "Inspect the change",
    categories: [
      { key: "physical", label: "Physical Change", color: "#0d9488", desc: "No new substance — usually reversible" },
      { key: "chemical", label: "Chemical Change", color: "#7c3aed", desc: "New substance forms — usually irreversible" },
    ],
    items: [
      { id: "ice", name: "Ice Melting to Water", shape: "crystal", color: "#bfdbfe", category: "physical", fact: "Ice and water are the same substance — only the state changes, and freezing reverses it. A physical change." },
      { id: "paperfold", name: "Folding a Paper Sheet", shape: "sheet", color: "#ffffff", category: "physical", fact: "Folding changes only the shape — it is still paper and can be unfolded. A physical change." },
      { id: "sugarwater", name: "Sugar Dissolving in Water", shape: "powder", color: "#ffffff", category: "physical", fact: "The sugar is still sugar — evaporate the water and you get it back. Dissolving is a physical change." },
      { id: "burntpaper", name: "Paper Burnt to Ash", shape: "lump", color: "#374151", category: "chemical", fact: "Burning turns paper into ash and smoke — new substances you cannot turn back into paper. A chemical change." },
      { id: "rustnail", name: "Iron Nail Rusting", shape: "nail", color: "#9a5b32", category: "chemical", fact: "The brown rust is a new substance formed from iron, air and moisture — rusting is a chemical change." },
      { id: "curd", name: "Milk Set into Curd", shape: "cup", color: "#fdf6e3", category: "chemical", fact: "Curd is a new substance with new taste and properties — you cannot change it back to milk. A chemical change." },
    ],
    question: {
      q: "Sugar dissolved in water can be recovered by evaporating the water. What kind of change is dissolving?",
      options: ["A physical change — no new substance is formed", "A chemical change — sugar becomes a new substance"],
      ans: 0,
      correctMsg: "Correct! The sugar is unchanged and can be recovered, so dissolving is a physical change.",
      incorrectMsg: "Think again — you can get the same sugar back by evaporation, so no new substance formed. Try again!",
    },
    conclusion: "Melting ice, folding paper and dissolving sugar form no new substance and are physical changes. Burning paper, rusting iron and milk turning to curd form new substances and are chemical changes.",
  },

  /* ───────── Class 7 · Physics — how heat travels ───────── */
  "heat-transfer": {
    id: "heat-transfer",
    title: "Heat Transfer: Conduction, Convection & Radiation",
    cls: "Class 7", subject: "Physics",
    chapter: "Ch 7 · Heat Transfer in Nature (NCERT Curiosity)",
    icon: "bolt", accent: "#ea580c", mode: "inspect",
    aim: "To examine everyday situations and identify how the heat is being transferred.",
    theory: "Heat flows through solids by conduction (particle to particle), through liquids and gases by convection (the heated fluid itself moves), and across empty space by radiation (no medium needed).",
    materials: ["Steel spoon in hot tea", "Boiling water", "Sunlight", "Room heater", "Hot pan handle", "Campfire warmth"],
    testVerb: "Study how the heat moves",
    categories: [
      { key: "conduction", label: "Conduction", color: "#0d9488", desc: "Through a solid, by touch" },
      { key: "convection", label: "Convection", color: "#0284c7", desc: "Hot liquid or air moves" },
      { key: "radiation", label: "Radiation", color: "#ea580c", desc: "Heat rays, no medium needed" },
    ],
    items: [
      { id: "spoon", name: "Steel Spoon in Hot Tea", shape: "spoon", color: "#cbd5e1", category: "conduction", fact: "Heat travels up the metal spoon particle by particle until the handle feels hot — that is conduction." },
      { id: "boiling", name: "Water Boiling in a Pan", shape: "cup", color: "#fca5a5", category: "convection", fact: "Hot water rises and cooler water sinks, setting up currents that heat all the water — convection." },
      { id: "sun", name: "Sunlight Warming the Ground", shape: "orb", color: "#fbbf24", category: "radiation", fact: "The Sun's heat crosses empty space with no medium at all — it reaches us by radiation." },
      { id: "heater", name: "Heater Warming a Room", shape: "panel", color: "#ef4444", category: "convection", fact: "Air warmed by the heater rises and cool air takes its place — the room heats by convection currents." },
      { id: "handle", name: "Iron Pan's Hot Handle", shape: "strip", color: "#475569", category: "conduction", fact: "The flame never touches the handle, yet heat is conducted along the metal to it — conduction." },
      { id: "campfire", name: "Warmth Beside a Campfire", shape: "lump", color: "#f97316", category: "radiation", fact: "Standing beside a fire you feel heat on your face directly — those are heat rays, radiation." },
    ],
    question: {
      q: "A frying pan gets a wooden handle. Why wood?",
      options: ["Wood is a poor conductor of heat, so the handle stays cool", "Wood radiates the heat away faster"],
      ans: 0,
      correctMsg: "Correct! Wood conducts heat poorly, so heat from the pan doesn't reach your hand — that's why handles are wooden or plastic.",
      incorrectMsg: "Not quite — wood doesn't 'radiate heat away'. It simply conducts heat very poorly, keeping the handle cool. Try again!",
    },
    conclusion: "Heat moves through the spoon and pan handle by conduction, through boiling water and room air by convection currents, and from the Sun and a campfire by radiation.",
  },

  /* ───────── Class 7 · Physics — luminous vs non-luminous ───────── */
  luminous: {
    id: "luminous",
    title: "Luminous & Non-Luminous Objects",
    cls: "Class 7", subject: "Physics",
    chapter: "Ch 11 · Light: Shadows and Reflections (NCERT Curiosity)",
    icon: "spark", accent: "#d97706", mode: "glow",
    aim: "To identify which objects emit their own light (luminous) and which only reflect light (non-luminous).",
    theory: "Objects that emit their own light — like the Sun, a glowing bulb or a candle flame — are luminous. Objects that do not emit light and are seen only because they reflect light are non-luminous.",
    materials: ["Sun model", "Electric bulb", "Candle", "Moon model", "Mirror", "Wooden block"],
    testVerb: "Test it in the dark",
    categories: [
      { key: "luminous", label: "Luminous", color: "#d97706", desc: "Emits its own light" },
      { key: "nonluminous", label: "Non-luminous", color: "#475569", desc: "Only reflects light" },
    ],
    items: [
      { id: "sun", name: "The Sun", shape: "orb", color: "#fbbf24", category: "luminous", fact: "The Sun shines with its own light — it is the brightest luminous object we know." },
      { id: "bulb", name: "Glowing Electric Bulb", shape: "bulb", color: "#fde68a", category: "luminous", fact: "Switched on, the bulb emits its own light — a luminous object." },
      { id: "candle", name: "Burning Candle", shape: "candle", color: "#fef3c7", category: "luminous", labelY: 0.45, fact: "The flame gives out its own light — a burning candle is luminous." },
      { id: "moon", name: "The Moon", shape: "orb", color: "#cbd5e1", category: "nonluminous", fact: "The Moon makes no light of its own — it only reflects sunlight, so it is non-luminous." },
      { id: "mirror", name: "Mirror", shape: "panel", color: "#e2e8f0", category: "nonluminous", fact: "A mirror is a brilliant reflector, but it emits no light of its own — non-luminous." },
      { id: "book", name: "Wooden Block", shape: "block", color: "#92623a", category: "nonluminous", fact: "In a dark room you cannot see it at all — it gives out no light. Non-luminous." },
    ],
    question: {
      q: "The Moon shines brightly at night. Is it luminous?",
      options: ["No — it only reflects the Sun's light", "Yes — it makes its own moonlight"],
      ans: 0,
      correctMsg: "Correct! Moonlight is reflected sunlight — the Moon emits no light of its own, so it is non-luminous.",
      incorrectMsg: "It looks bright, but that light is borrowed — the Moon only reflects sunlight. Try again!",
    },
    conclusion: "The Sun, a glowing bulb and a candle flame emit their own light and are luminous. The Moon, a mirror and a wooden block only reflect light and are non-luminous.",
  },

  /* ───────── Class 8 · Chemistry — examine properties ───────── */
  "metals-nonmetals": {
    id: "metals-nonmetals",
    title: "Metals & Non-Metals",
    cls: "Class 8", subject: "Chemistry",
    chapter: "Ch 4 · Materials: Metals and Non-Metals",
    icon: "flask", accent: "#d97706", mode: "examine",
    aim: "To classify materials as metals or non-metals by examining their properties (lustre & conductivity).",
    theory: "Metals are lustrous, malleable, ductile, sonorous and conduct electricity. Non-metals are dull, brittle and poor conductors.",
    materials: ["Iron nail", "Copper wire", "Aluminium strip", "Sulphur", "Carbon (coal)", "Phosphorus", "Conductivity tester"],
    testVerb: "Touch to the tester",
    categories: [
      { key: "metal", label: "Metal", color: "#d97706", desc: "Shiny & conducts — bulb glows" },
      { key: "nonmetal", label: "Non-metal", color: "#7c3aed", desc: "Dull & does not conduct" },
    ],
    items: [
      { id: "iron", name: "Iron Nail", shape: "nail", color: "#8a8f98", category: "metal", fact: "Shiny, hard, and the bulb glows — iron conducts electricity. It is a metal." },
      { id: "copper", name: "Copper Wire", shape: "wire", color: "#b45309", category: "metal", fact: "Lustrous, ductile and a great conductor — the bulb glows brightly. Copper is a metal." },
      { id: "aluminium", name: "Aluminium Strip", shape: "strip", color: "#cbd5e1", category: "metal", fact: "Malleable and conducting — the bulb glows. Aluminium is a metal." },
      { id: "sulphur", name: "Sulphur", shape: "lump", color: "#eab308", category: "nonmetal", fact: "Dull yellow and brittle — the bulb stays off. Sulphur is a non-metal." },
      { id: "carbon", name: "Carbon (Coal)", shape: "lump", color: "#374151", category: "nonmetal", fact: "Dull and brittle — does not conduct (the bulb is off). Carbon is a non-metal." },
      { id: "phosphorus", name: "Phosphorus", shape: "lump", color: "#fca5a5", category: "nonmetal", fact: "Soft, dull and non-conducting — the bulb stays off. Phosphorus is a non-metal." },
    ],
    question: {
      q: "A material can be beaten into thin sheets. This property is called…",
      options: ["Malleability", "Sonority"],
      ans: 0,
      correctMsg: "Correct! Malleability is being beaten into thin sheets — a key property of metals like aluminium and silver.",
      incorrectMsg: "Close — sonority means producing a ringing sound. Being beaten into sheets is 'malleability'. Try again!",
    },
    conclusion: "Iron, copper and aluminium are lustrous and conduct electricity (metals). Sulphur, carbon and phosphorus are dull and non-conducting (non-metals).",
  },
};
