/* ── NCERT-grounded lab specifications (data-driven 3D classification labs) ──
   Sources: NCERT Class 6 "Curiosity" (2024) & NCERT Class 8 Science.
   Each item carries a `shape` (3D model) + `color`; each lab a `mode` that
   drives the real-world test process (magnet test / dissolving in water /
   examining properties). Driven by genlab3d.jsx + labitems3d.jsx. */

export const GEN_LABS = {
  /* ───────── Class 6 · Chemistry — dissolve in water ───────── */
  solubility: {
    id: "solubility",
    title: "Soluble & Insoluble Substances",
    cls: "Class 6", subject: "Chemistry",
    chapter: "Methods of Separation of Substances (NCERT Curiosity)",
    icon: "beaker", accent: "#0d9488", mode: "water",
    aim: "To test whether different everyday substances are soluble or insoluble in water.",
    theory: "A substance that dissolves completely in water forms a clear solution and is soluble. One that does not dissolve and settles or floats is insoluble.",
    materials: ["Beaker of water", "Stirring rod", "Sugar", "Common salt", "Sand", "Chalk powder", "Copper sulphate", "Cooking oil"],
    testVerb: "Add to water & stir",
    categories: [
      { key: "soluble", label: "Soluble", color: "#0d9488", desc: "Dissolves fully — clear solution" },
      { key: "insoluble", label: "Insoluble", color: "#ea580c", desc: "Does not dissolve — stays visible" },
    ],
    items: [
      { id: "sugar", name: "Sugar", shape: "powder", color: "#ffffff", category: "soluble", fact: "The sugar disappears and the water stays clear — sugar is soluble in water." },
      { id: "salt", name: "Common Salt", shape: "powder", color: "#eef2f7", category: "soluble", fact: "The salt dissolves completely into a clear solution — salt is soluble." },
      { id: "coppersulphate", name: "Copper Sulphate", shape: "crystal", color: "#3b82f6", category: "soluble", fact: "It dissolves and turns the water blue — copper sulphate is soluble." },
      { id: "sand", name: "Sand", shape: "grains", color: "#c2a878", category: "insoluble", fact: "The sand settles at the bottom and the water stays murky — sand is insoluble." },
      { id: "chalk", name: "Chalk Powder", shape: "powder", color: "#e2e8f0", category: "insoluble", fact: "The chalk makes the water cloudy and settles down — chalk is insoluble." },
      { id: "oil", name: "Cooking Oil", shape: "liquid", color: "#f4d03f", category: "insoluble", fact: "The oil floats on top and won't mix — oil is insoluble in water." },
    ],
    question: {
      q: "Why does sugar seem to 'disappear' when stirred into water?",
      options: ["It dissolves — its particles spread evenly between the water particles", "It reacts with water and turns into a gas"],
      ans: 0,
      correctMsg: "Exactly! Soluble substances break into tiny particles that spread evenly among the water particles, forming a clear solution.",
      incorrectMsg: "Not quite — sugar doesn't turn into gas. It dissolves: its particles spread between the water particles. Try again!",
    },
    conclusion: "Sugar, salt and copper sulphate dissolve in water (soluble). Sand, chalk and oil do not dissolve (insoluble). Insoluble solids can later be separated by filtration.",
  },

  /* ───────── Class 6 · Physics — magnet test ───────── */
  magnetism: {
    id: "magnetism",
    title: "Magnetic & Non-Magnetic Materials",
    cls: "Class 6", subject: "Physics",
    chapter: "Ch 4 · Exploring Magnets (NCERT Curiosity)",
    icon: "atom", accent: "#4f46e5", mode: "magnet",
    aim: "To find which materials are attracted by a magnet (magnetic) and which are not (non-magnetic).",
    theory: "Materials attracted to a magnet are magnetic — iron, cobalt and nickel are magnetic. Materials not attracted are non-magnetic.",
    materials: ["Bar magnet", "Iron nail", "Steel pin", "Nickel coin", "Aluminium foil", "Copper wire", "Plastic scale"],
    testVerb: "Bring the magnet near",
    categories: [
      { key: "magnetic", label: "Magnetic", color: "#4f46e5", desc: "Jumps to the magnet" },
      { key: "nonmagnetic", label: "Non-magnetic", color: "#64748b", desc: "Not attracted" },
    ],
    items: [
      { id: "ironnail", name: "Iron Nail", shape: "nail", color: "#8a8f98", category: "magnetic", fact: "The nail jumps and sticks to the magnet — iron is magnetic!" },
      { id: "steelpin", name: "Steel Pin", shape: "pin", color: "#cbd5e1", category: "magnetic", fact: "The pin is pulled to the magnet — steel (mostly iron) is magnetic." },
      { id: "nickel", name: "Nickel Coin", shape: "coin", color: "#aeb4bd", category: "magnetic", fact: "It clings to the magnet — nickel is one of the few magnetic metals." },
      { id: "aluminium", name: "Aluminium Foil", shape: "foil", color: "#d4d8de", category: "nonmagnetic", fact: "Nothing happens — aluminium is non-magnetic." },
      { id: "copper", name: "Copper Wire", shape: "wire", color: "#b45309", category: "nonmagnetic", fact: "The magnet has no effect — copper is non-magnetic." },
      { id: "plastic", name: "Plastic Scale", shape: "ruler", color: "#60a5fa", category: "nonmagnetic", fact: "No attraction at all — plastic is non-magnetic." },
    ],
    question: {
      q: "Iron, cobalt and nickel are attracted to magnets. What do we call such materials?",
      options: ["Magnetic materials", "Conductors"],
      ans: 0,
      correctMsg: "Correct! Materials attracted by a magnet are called magnetic materials — iron, cobalt and nickel are the common ones.",
      incorrectMsg: "Not quite — conductors carry electricity. Materials attracted by a magnet are 'magnetic materials'. Try again!",
    },
    conclusion: "The iron nail, steel pin and nickel coin are attracted by the magnet (magnetic). Aluminium, copper and plastic are not attracted (non-magnetic).",
  },

  /* ───────── Class 6 · Chemistry — torch light test ───────── */
  "materials-light": {
    id: "materials-light",
    title: "Transparent, Translucent & Opaque",
    cls: "Class 6", subject: "Chemistry",
    chapter: "Ch 6 · Materials Around Us (NCERT Curiosity)",
    icon: "eye", accent: "#0284c7", mode: "light",
    aim: "To group materials by how much light passes through them — transparent, translucent or opaque.",
    theory: "Materials we can see through clearly are transparent. Materials we can see through only partially are translucent. Materials we cannot see through at all are opaque.",
    materials: ["Torch", "White screen", "Glass slab", "Glass of water", "Butter paper", "Frosted glass", "Wooden block", "Steel plate"],
    testVerb: "Shine the torch through",
    categories: [
      { key: "transparent", label: "Transparent", color: "#0284c7", desc: "Light passes fully — clear bright spot" },
      { key: "translucent", label: "Translucent", color: "#d97706", desc: "Some light passes — dim, fuzzy glow" },
      { key: "opaque", label: "Opaque", color: "#475569", desc: "No light passes — a shadow forms" },
    ],
    items: [
      { id: "glass", name: "Glass Slab", shape: "slab", color: "#dbeafe", category: "transparent", fact: "The beam passes straight through and makes a bright, sharp spot on the screen — glass is transparent." },
      { id: "water", name: "Glass of Water", shape: "cup", color: "#bfe3f0", category: "transparent", fact: "Light travels through the clear water and lights up the screen — water is transparent." },
      { id: "butter", name: "Butter Paper", shape: "sheet", color: "#fef9c3", category: "translucent", fact: "Only some light gets through, making a dim fuzzy glow — butter paper is translucent." },
      { id: "frosted", name: "Frosted Glass", shape: "frosted", color: "#cbd5e1", category: "translucent", fact: "The light scatters into a soft blur on the screen — frosted glass is translucent." },
      { id: "wood", name: "Wooden Block", shape: "block", color: "#92623a", category: "opaque", fact: "No light reaches the screen — only a dark shadow. Wood is opaque." },
      { id: "steel", name: "Steel Plate", shape: "panel", color: "#cbd5e1", category: "opaque", fact: "The metal blocks the beam completely and casts a shadow — steel is opaque." },
    ],
    question: {
      q: "Why can we see clearly through a glass slab but not through a wooden block?",
      options: ["Glass lets light pass through it; wood blocks light completely", "Glass is colder than wood"],
      ans: 0,
      correctMsg: "Exactly! Seeing through a material is about light passing through it — transparent materials let light through, opaque ones block it.",
      incorrectMsg: "Not quite — temperature has nothing to do with it. It's about whether light can pass through. Try again!",
    },
    conclusion: "Glass and water let light pass fully (transparent). Butter paper and frosted glass let some light through (translucent). Wood and steel block light completely (opaque).",
  },

  /* ───────── Class 6 · Chemistry — choose the separation method ───────── */
  separation: {
    id: "separation",
    title: "Methods of Separation",
    cls: "Class 6", subject: "Chemistry",
    chapter: "Ch 9 · Methods of Separation in Everyday Life (NCERT Curiosity)",
    icon: "beaker", accent: "#d97706", mode: "inspect",
    aim: "To choose the correct method for separating the components of everyday mixtures.",
    theory: "We pick a separation method using differences between the components: size or colour (handpicking), weight in moving air (winnowing), particle size with a mesh (sieving), or an insoluble solid in a liquid (filtration).",
    materials: ["Magnifier", "Mixture samples", "Sieve", "Filter paper & funnel", "Winnowing tray"],
    testVerb: "Inspect the mixture",
    categories: [
      { key: "handpicking", label: "Handpicking", color: "#0d9488", desc: "Few large, different-looking pieces" },
      { key: "winnowing", label: "Winnowing", color: "#0284c7", desc: "Lighter part blows away in wind" },
      { key: "sieving", label: "Sieving", color: "#7c3aed", desc: "Different particle sizes — use a mesh" },
      { key: "filtration", label: "Filtration", color: "#d97706", desc: "Insoluble solid in a liquid" },
    ],
    items: [
      { id: "stones", name: "Stones in Rice", shape: "mixture", color: "#f5f0e6", category: "handpicking", fact: "The stones are few, larger and look different from the rice — simply pick them out by hand." },
      { id: "husk", name: "Husk & Grain", shape: "mixture", color: "#d9b98a", category: "winnowing", fact: "Husk is much lighter than grain — wind carries the husk away while grain falls straight down. That is winnowing." },
      { id: "bran", name: "Bran in Flour", shape: "powder", color: "#efe3cd", category: "sieving", fact: "Fine flour falls through the mesh while the coarser bran stays behind — sieving separates by particle size." },
      { id: "tea", name: "Tea Leaves in Tea", shape: "specks", color: "#b4762d", category: "filtration", fact: "The liquid tea passes through a strainer while the insoluble leaves are caught — that's filtration." },
      { id: "sandwater", name: "Sand in Water", shape: "specks", color: "#9fb6c1", category: "filtration", fact: "Insoluble sand is trapped by filter paper while clear water passes through — filtration gives clean water." },
      { id: "pebbles", name: "Pebbles in Sand", shape: "mixture", color: "#d9c49a", category: "sieving", fact: "Sand slips through the sieve's holes while the larger pebbles stay on top — sieving works by size." },
    ],
    question: {
      q: "In winnowing, why does the husk separate from the grain?",
      options: ["Husk is lighter, so moving air carries it away", "Husk dissolves in the air"],
      ans: 0,
      correctMsg: "Correct! Winnowing works because the lighter husk is carried away by wind while heavier grains fall straight down.",
      incorrectMsg: "Not quite — nothing dissolves in air here. The husk is simply lighter, so the wind carries it away. Try again!",
    },
    conclusion: "Stones in rice are handpicked; husk is winnowed away from grain; bran and pebbles are sieved out by size; tea leaves and sand are removed from liquids by filtration.",
  },

  /* ───────── Class 6 · Physics — types of motion ───────── */
  motion: {
    id: "motion",
    title: "Types of Motion",
    cls: "Class 6", subject: "Physics",
    chapter: "Ch 5 · Measurement of Length and Motion (NCERT Curiosity)",
    icon: "refresh", accent: "#dc2626", mode: "motion",
    aim: "To observe moving objects and classify their motion as linear, circular or oscillatory.",
    theory: "Motion along a straight line is linear motion. Motion along a circular path is circular motion. To-and-fro motion about a fixed position is oscillatory motion.",
    materials: ["Toy car", "Rolling ball", "Table fan", "Spinning top", "Pendulum", "Swing model"],
    testVerb: "Tap to set it moving",
    categories: [
      { key: "linear", label: "Linear", color: "#0d9488", desc: "Straight-line motion" },
      { key: "circular", label: "Circular", color: "#7c3aed", desc: "Moves along a circle" },
      { key: "oscillatory", label: "Oscillatory", color: "#d97706", desc: "To-and-fro about a point" },
    ],
    items: [
      { id: "car", name: "Toy Car", shape: "car", color: "#dc2626", category: "linear", fact: "The car moves along a straight path on the bench — this is linear motion." },
      { id: "ball", name: "Rolling Ball", shape: "ball", color: "#f59e0b", category: "linear", fact: "The ball rolls along a straight line — its motion is linear (the ball itself also spins as it rolls!)." },
      { id: "fan", name: "Table Fan", shape: "fan", color: "#60a5fa", category: "circular", labelY: 0.62, fact: "Each blade moves round and round along a circle — the fan shows circular motion." },
      { id: "top", name: "Spinning Top", shape: "top", color: "#7c3aed", category: "circular", fact: "Every point of the top moves in a circle about its spike — circular (rotational) motion." },
      { id: "pendulum", name: "Pendulum", shape: "pendulum", color: "#d97706", category: "oscillatory", labelY: 0.68, fact: "The bob swings to and fro about its rest position — this is oscillatory motion." },
      { id: "swing", name: "Swing", shape: "swing", color: "#dc2626", category: "oscillatory", labelY: 0.62, fact: "The swing moves back and forth again and again — oscillatory motion, just like in a park." },
    ],
    question: {
      q: "A point marked on a moving fan blade traces a circle. What type of motion is this?",
      options: ["Circular motion", "Linear motion"],
      ans: 0,
      correctMsg: "Correct! Any point on the blade moves along a circular path around the centre — that's circular motion.",
      incorrectMsg: "Look again at the path — it goes round and round in a circle, not in a straight line. Try again!",
    },
    conclusion: "The toy car and rolling ball move in straight lines (linear motion). The fan blades and spinning top move along circles (circular motion). The pendulum and swing move to and fro (oscillatory motion).",
  },

  /* ───────── Class 6 · Physics — read the thermometer ───────── */
  temperature: {
    id: "temperature",
    title: "Temperature & Its Measurement",
    cls: "Class 6", subject: "Physics",
    chapter: "Ch 7 · Temperature and its Measurement (NCERT Curiosity)",
    icon: "drop", accent: "#0f766e", mode: "thermo",
    aim: "To measure the temperature of different water samples with a laboratory thermometer and classify them as cold, warm or hot.",
    theory: "Temperature is the measure of how hot or cold something is, measured with a thermometer in degrees Celsius (°C). Our sense of touch is unreliable — only a thermometer gives the true reading.",
    materials: ["Laboratory thermometer (−10 °C to 110 °C)", "Water samples in glasses"],
    testVerb: "Dip the thermometer",
    categories: [
      { key: "cold", label: "Cold (≤10°C)", color: "#2563eb", desc: "At or below 10 °C" },
      { key: "warm", label: "Warm (11–45°C)", color: "#0d9488", desc: "Between 11 and 45 °C" },
      { key: "hot", label: "Hot (>45°C)", color: "#dc2626", desc: "Above 45 °C" },
    ],
    items: [
      { id: "icewater", name: "Ice-Water Mix", shape: "cup", color: "#bfdbfe", category: "cold", temp: 0, fact: "The thermometer reads 0 degrees Celsius — melting ice and water stay at 0 °C. That's cold!" },
      { id: "chilled", name: "Chilled Lemonade", shape: "cup", color: "#fef08a", category: "cold", temp: 8, fact: "It reads 8 degrees Celsius — refrigerator-cold. Below 10 °C counts as cold." },
      { id: "tap", name: "Tap Water", shape: "cup", color: "#bae6fd", category: "warm", temp: 25, fact: "The mercury settles at 25 degrees Celsius — about room temperature. That's in the warm range." },
      { id: "body", name: "Body-Warm Water", shape: "cup", color: "#a7f3d0", category: "warm", temp: 37, fact: "It reads 37 degrees Celsius — the same as normal human body temperature." },
      { id: "milk", name: "Hot Milk", shape: "cup", color: "#fef3c7", category: "hot", temp: 60, fact: "The column rises to 60 degrees Celsius — too hot to sip quickly! Above 45 °C is hot." },
      { id: "boiling", name: "Boiling Water", shape: "cup", color: "#fecaca", category: "hot", temp: 100, fact: "The thermometer shoots up to 100 degrees Celsius — water boils at 100 °C at sea level." },
    ],
    question: {
      q: "A clinical thermometer reads only 35–42 °C. Why such a small range?",
      options: ["Because human body temperature stays within that range", "Because mercury freezes below 35 °C"],
      ans: 0,
      correctMsg: "Correct! A clinical thermometer is made only for body temperature, which stays near 37 °C — so its scale is just 35–42 °C.",
      incorrectMsg: "Not quite — mercury freezes far below that, at −39 °C. The range matches human body temperature. Try again!",
    },
    conclusion: "A laboratory thermometer measures each sample in °C: ice-water (0°) and chilled drinks are cold; tap water (25°) and body-warm water (37°) are warm; hot milk (60°) and boiling water (100°) are hot. Touch can deceive — the thermometer never does.",
  },

  /* ───────── Class 7 · Chemistry — physical vs chemical changes ───────── */
  changes: {
    id: "changes",
    title: "Physical & Chemical Changes",
    cls: "Class 7", subject: "Chemistry",
    chapter: "Ch 5 · Changes Around Us: Physical and Chemical (NCERT Curiosity)",
    icon: "refresh", accent: "#7c3aed", mode: "inspect",
    aim: "To examine everyday changes and classify them as physical or chemical changes.",
    theory: "In a physical change no new substance is formed — often only shape, size or state changes, and it can usually be reversed. In a chemical change a new substance with new properties is formed, and it usually cannot be reversed.",
    materials: ["Magnifier", "Ice cubes", "Paper", "Sugar & water", "Burnt paper ash", "Rusted iron nail", "Curd set from milk"],
    testVerb: "Inspect the change",
    categories: [
      { key: "physical", label: "Physical Change", color: "#0d9488", desc: "No new substance — usually reversible" },
      { key: "chemical", label: "Chemical Change", color: "#7c3aed", desc: "New substance forms — usually irreversible" },
    ],
    items: [
      { id: "ice", name: "Ice Melting to Water", shape: "crystal", color: "#bfdbfe", category: "physical", fact: "Ice and water are the same substance — only the state changes, and freezing reverses it. A physical change." },
      { id: "paperfold", name: "Folding a Paper Sheet", shape: "sheet", color: "#ffffff", category: "physical", fact: "Folding changes only the shape — it is still paper and can be unfolded. A physical change." },
      { id: "sugarwater", name: "Sugar Dissolving in Water", shape: "powder", color: "#ffffff", category: "physical", fact: "The sugar is still sugar — evaporate the water and you get it back. Dissolving is a physical change." },
      { id: "burntpaper", name: "Paper Burnt to Ash", shape: "lump", color: "#374151", category: "chemical", fact: "Burning turns paper into ash and smoke — new substances you cannot turn back into paper. A chemical change." },
      { id: "rustnail", name: "Iron Nail Rusting", shape: "nail", color: "#9a5b32", category: "chemical", fact: "The brown rust is a new substance formed from iron, air and moisture — rusting is a chemical change." },
      { id: "curd", name: "Milk Set into Curd", shape: "cup", color: "#fdf6e3", category: "chemical", fact: "Curd is a new substance with new taste and properties — you cannot change it back to milk. A chemical change." },
    ],
    question: {
      q: "Sugar dissolved in water can be recovered by evaporating the water. What kind of change is dissolving?",
      options: ["A physical change — no new substance is formed", "A chemical change — sugar becomes a new substance"],
      ans: 0,
      correctMsg: "Correct! The sugar is unchanged and can be recovered, so dissolving is a physical change.",
      incorrectMsg: "Think again — you can get the same sugar back by evaporation, so no new substance formed. Try again!",
    },
    conclusion: "Melting ice, folding paper and dissolving sugar form no new substance and are physical changes. Burning paper, rusting iron and milk turning to curd form new substances and are chemical changes.",
  },

  /* ───────── Class 7 · Chemistry — neutralisation in everyday life ───────── */
  neutralise: {
    id: "neutralise",
    title: "Neutralisation in Everyday Life",
    cls: "Class 7", subject: "Chemistry",
    chapter: "Ch 5 · Acids, Bases and Salts (NCERT Curiosity)",
    icon: "flask", accent: "#dc2626", mode: "mix",
    aim: "To decide, for each everyday situation, whether the trouble is caused by an acid or a base — and so whether we should add a base or an acid to neutralise it.",
    theory: "When an acid and a base are mixed in the right amount they react to form a salt and water, cancelling each other out — this is neutralisation. So an acidic problem is cured by adding a base, and a basic (alkaline) problem is cured by adding an acid. A universal indicator turns green when the solution becomes neutral.",
    materials: ["Beaker of universal-indicator solution", "Dropper of dilute base", "Dropper of dilute acid", "Everyday samples — sting fluid, stomach acid, soil water, factory effluent"],
    testVerb: "Neutralise the sample",
    categories: [
      { key: "addbase", label: "Add a Base", color: "#5a4fc4", desc: "The sample is acidic — a base neutralises it" },
      { key: "addacid", label: "Add an Acid", color: "#e8443a", desc: "The sample is basic — an acid neutralises it" },
    ],
    items: [
      { id: "acidity", name: "Stomach Acidity", shape: "cup", color: "#f3a39a", category: "addbase", fact: "Indigestion comes from excess hydrochloric acid in the stomach. A mild base — an antacid such as milk of magnesia — neutralises it. We add a base." },
      { id: "antsting", name: "Ant or Bee Sting", shape: "cup", color: "#f2b0a8", category: "addbase", fact: "An ant or bee sting injects formic acid, which is acidic. Rubbing baking soda — a mild base — on the spot neutralises the acid. We add a base." },
      { id: "acidicsoil", name: "Acidic Soil", shape: "cup", color: "#eda69c", category: "addbase", fact: "Soil that is too acidic for crops is treated with quicklime or slaked lime — bases that raise the pH towards neutral. We add a base." },
      { id: "waspsting", name: "Wasp Sting", shape: "cup", color: "#c4b6ef", category: "addacid", fact: "Unlike a bee sting, a wasp sting is alkaline (basic). Dabbing a mild acid like vinegar neutralises it. We add an acid." },
      { id: "basicsoil", name: "Alkaline Soil", shape: "cup", color: "#bcace9", category: "addacid", fact: "Soil that is too basic is corrected by mixing in organic manure or compost, which is mildly acidic. We add an acid." },
      { id: "factory", name: "Alkaline Factory Waste", shape: "cup", color: "#c0b0ec", category: "addacid", fact: "Before strongly basic factory effluent is released, it is treated with an acid so it no longer harms rivers and aquatic life. We add an acid." },
    ],
    question: {
      q: "A wasp sting is alkaline. Which kitchen item would best soothe it?",
      options: ["Vinegar — a mild acid", "Baking soda — a mild base"],
      ans: 0,
      correctMsg: "Correct! A wasp sting is basic, so a mild acid like vinegar neutralises it. (Baking soda is for acidic ant and bee stings.)",
      incorrectMsg: "Careful — the sting is already basic, so adding another base won't help. A mild acid like vinegar neutralises it. Try again!",
    },
    conclusion: "Acidic troubles — stomach acidity, ant and bee stings, and acidic soil — are cured by adding a base. Basic troubles — wasp stings, alkaline soil and alkaline factory waste — are cured by adding an acid. In every case the acid and base react to form a salt and water, turning the indicator neutral green.",
  },

  /* ───────── Class 7 · Physics — how heat travels ───────── */
  "heat-transfer": {
    id: "heat-transfer",
    title: "Heat Transfer: Conduction, Convection & Radiation",
    cls: "Class 7", subject: "Physics",
    chapter: "Ch 7 · Heat Transfer in Nature (NCERT Curiosity)",
    icon: "bolt", accent: "#ea580c", mode: "inspect",
    aim: "To examine everyday situations and identify how the heat is being transferred.",
    theory: "Heat flows through solids by conduction (particle to particle), through liquids and gases by convection (the heated fluid itself moves), and across empty space by radiation (no medium needed).",
    materials: ["Steel spoon in hot tea", "Boiling water", "Sunlight", "Room heater", "Hot pan handle", "Campfire warmth"],
    testVerb: "Study how the heat moves",
    categories: [
      { key: "conduction", label: "Conduction", color: "#0d9488", desc: "Through a solid, by touch" },
      { key: "convection", label: "Convection", color: "#0284c7", desc: "Hot liquid or air moves" },
      { key: "radiation", label: "Radiation", color: "#ea580c", desc: "Heat rays, no medium needed" },
    ],
    items: [
      { id: "spoon", name: "Steel Spoon in Hot Tea", shape: "spoon", color: "#cbd5e1", category: "conduction", fact: "Heat travels up the metal spoon particle by particle until the handle feels hot — that is conduction." },
      { id: "boiling", name: "Water Boiling in a Pan", shape: "cup", color: "#fca5a5", category: "convection", fact: "Hot water rises and cooler water sinks, setting up currents that heat all the water — convection." },
      { id: "sun", name: "Sunlight Warming the Ground", shape: "orb", color: "#fbbf24", category: "radiation", fact: "The Sun's heat crosses empty space with no medium at all — it reaches us by radiation." },
      { id: "heater", name: "Heater Warming a Room", shape: "panel", color: "#ef4444", category: "convection", fact: "Air warmed by the heater rises and cool air takes its place — the room heats by convection currents." },
      { id: "handle", name: "Iron Pan's Hot Handle", shape: "strip", color: "#475569", category: "conduction", fact: "The flame never touches the handle, yet heat is conducted along the metal to it — conduction." },
      { id: "campfire", name: "Warmth Beside a Campfire", shape: "lump", color: "#f97316", category: "radiation", fact: "Standing beside a fire you feel heat on your face directly — those are heat rays, radiation." },
    ],
    question: {
      q: "A frying pan gets a wooden handle. Why wood?",
      options: ["Wood is a poor conductor of heat, so the handle stays cool", "Wood radiates the heat away faster"],
      ans: 0,
      correctMsg: "Correct! Wood conducts heat poorly, so heat from the pan doesn't reach your hand — that's why handles are wooden or plastic.",
      incorrectMsg: "Not quite — wood doesn't 'radiate heat away'. It simply conducts heat very poorly, keeping the handle cool. Try again!",
    },
    conclusion: "Heat moves through the spoon and pan handle by conduction, through boiling water and room air by convection currents, and from the Sun and a campfire by radiation.",
  },

  /* ───────── Class 7 · Physics — luminous vs non-luminous ───────── */
  luminous: {
    id: "luminous",
    title: "Luminous & Non-Luminous Objects",
    cls: "Class 7", subject: "Physics",
    chapter: "Ch 11 · Light: Shadows and Reflections (NCERT Curiosity)",
    icon: "spark", accent: "#d97706", mode: "glow",
    aim: "To identify which objects emit their own light (luminous) and which only reflect light (non-luminous).",
    theory: "Objects that emit their own light — like the Sun, a glowing bulb or a candle flame — are luminous. Objects that do not emit light and are seen only because they reflect light are non-luminous.",
    materials: ["Sun model", "Electric bulb", "Candle", "Moon model", "Mirror", "Wooden block"],
    testVerb: "Test it in the dark",
    categories: [
      { key: "luminous", label: "Luminous", color: "#d97706", desc: "Emits its own light" },
      { key: "nonluminous", label: "Non-luminous", color: "#475569", desc: "Only reflects light" },
    ],
    items: [
      { id: "sun", name: "The Sun", shape: "orb", color: "#fbbf24", category: "luminous", fact: "The Sun shines with its own light — it is the brightest luminous object we know." },
      { id: "bulb", name: "Glowing Electric Bulb", shape: "bulb", color: "#fde68a", category: "luminous", fact: "Switched on, the bulb emits its own light — a luminous object." },
      { id: "candle", name: "Burning Candle", shape: "candle", color: "#fef3c7", category: "luminous", labelY: 0.45, fact: "The flame gives out its own light — a burning candle is luminous." },
      { id: "moon", name: "The Moon", shape: "orb", color: "#cbd5e1", category: "nonluminous", fact: "The Moon makes no light of its own — it only reflects sunlight, so it is non-luminous." },
      { id: "mirror", name: "Mirror", shape: "panel", color: "#e2e8f0", category: "nonluminous", fact: "A mirror is a brilliant reflector, but it emits no light of its own — non-luminous." },
      { id: "book", name: "Wooden Block", shape: "block", color: "#92623a", category: "nonluminous", fact: "In a dark room you cannot see it at all — it gives out no light. Non-luminous." },
    ],
    question: {
      q: "The Moon shines brightly at night. Is it luminous?",
      options: ["No — it only reflects the Sun's light", "Yes — it makes its own moonlight"],
      ans: 0,
      correctMsg: "Correct! Moonlight is reflected sunlight — the Moon emits no light of its own, so it is non-luminous.",
      incorrectMsg: "It looks bright, but that light is borrowed — the Moon only reflects sunlight. Try again!",
    },
    conclusion: "The Sun, a glowing bulb and a candle flame emit their own light and are luminous. The Moon, a mirror and a wooden block only reflect light and are non-luminous.",
  },

  /* ───────── Class 8 · Chemistry — examine properties ───────── */
  "metals-nonmetals": {
    id: "metals-nonmetals",
    title: "Metals & Non-Metals",
    cls: "Class 8", subject: "Chemistry",
    chapter: "Ch 4 · Materials: Metals and Non-Metals",
    icon: "flask", accent: "#d97706", mode: "examine",
    aim: "To classify materials as metals or non-metals by examining their properties (lustre & conductivity).",
    theory: "Metals are lustrous, malleable, ductile, sonorous and conduct electricity. Non-metals are dull, brittle and poor conductors.",
    materials: ["Iron nail", "Copper wire", "Aluminium strip", "Sulphur", "Carbon (coal)", "Phosphorus", "Conductivity tester"],
    testVerb: "Touch to the tester",
    categories: [
      { key: "metal", label: "Metal", color: "#d97706", desc: "Shiny & conducts — bulb glows" },
      { key: "nonmetal", label: "Non-metal", color: "#7c3aed", desc: "Dull & does not conduct" },
    ],
    items: [
      { id: "iron", name: "Iron Nail", shape: "nail", color: "#8a8f98", category: "metal", fact: "Shiny, hard, and the bulb glows — iron conducts electricity. It is a metal." },
      { id: "copper", name: "Copper Wire", shape: "wire", color: "#b45309", category: "metal", fact: "Lustrous, ductile and a great conductor — the bulb glows brightly. Copper is a metal." },
      { id: "aluminium", name: "Aluminium Strip", shape: "strip", color: "#cbd5e1", category: "metal", fact: "Malleable and conducting — the bulb glows. Aluminium is a metal." },
      { id: "sulphur", name: "Sulphur", shape: "lump", color: "#eab308", category: "nonmetal", fact: "Dull yellow and brittle — the bulb stays off. Sulphur is a non-metal." },
      { id: "carbon", name: "Carbon (Coal)", shape: "lump", color: "#374151", category: "nonmetal", fact: "Dull and brittle — does not conduct (the bulb is off). Carbon is a non-metal." },
      { id: "phosphorus", name: "Phosphorus", shape: "lump", color: "#fca5a5", category: "nonmetal", fact: "Soft, dull and non-conducting — the bulb stays off. Phosphorus is a non-metal." },
    ],
    question: {
      q: "A material can be beaten into thin sheets. This property is called…",
      options: ["Malleability", "Sonority"],
      ans: 0,
      correctMsg: "Correct! Malleability is being beaten into thin sheets — a key property of metals like aluminium and silver.",
      incorrectMsg: "Close — sonority means producing a ringing sound. Being beaten into sheets is 'malleability'. Try again!",
    },
    conclusion: "Iron, copper and aluminium are lustrous and conduct electricity (metals). Sulphur, carbon and phosphorus are dull and non-conducting (non-metals).",
  },

  /* ───────── Class 8 · Chemistry — rusting of iron ───────── */
  rusting: {
    id: "rusting",
    title: "Rusting of Iron",
    cls: "Class 8", subject: "Chemistry",
    chapter: "Ch 4 · Materials: Metals and Non-Metals",
    icon: "atom", accent: "#b45309", mode: "rust",
    aim: "To find out which conditions cause an iron nail to rust and which keep it shiny.",
    theory: "Rusting is a chemical change in which iron reacts with the oxygen of the air in the presence of moisture (water) to form a reddish-brown coating called rust. If either air or moisture is kept away, iron does not rust. Salt speeds rusting up.",
    materials: ["Iron nails", "Test tubes", "Tap water", "Common salt", "Cooking oil", "Anhydrous calcium chloride (drying agent)", "Paint"],
    testVerb: "Observe the set-up over days",
    categories: [
      { key: "rusts", label: "Rusts", color: "#b45309", desc: "Air + moisture present" },
      { key: "norust", label: "Stays Shiny", color: "#0d9488", desc: "Air or moisture shut out" },
    ],
    items: [
      { id: "openwater", name: "Nail in Tap Water (open)", shape: "nail", color: "#c3c7cd", category: "rusts", fact: "Open to air and standing in water, the nail meets both oxygen and moisture — so it rusts." },
      { id: "saltwater", name: "Nail in Salt Water", shape: "nail", color: "#c3c7cd", category: "rusts", fact: "Air, water and salt together — salt makes iron rust even faster. It rusts." },
      { id: "dampair", name: "Nail in Damp Air", shape: "nail", color: "#c3c7cd", category: "rusts", fact: "Humid air carries both oxygen and moisture, so even without standing water the nail rusts." },
      { id: "oilsealed", name: "Nail in Boiled Water + Oil", shape: "nail", color: "#c3c7cd", category: "norust", fact: "Boiling drives the air out of the water and a layer of oil seals fresh air out — no oxygen, so no rust." },
      { id: "dryair", name: "Nail in Dry Air (CaCl₂)", shape: "nail", color: "#c3c7cd", category: "norust", fact: "Calcium chloride soaks up all the moisture, leaving dry air. With no water, the nail stays shiny." },
      { id: "painted", name: "Painted Nail", shape: "nail", color: "#c3c7cd", category: "norust", fact: "A coat of paint keeps air and moisture from touching the iron — that is why we paint gates and railings. No rust." },
    ],
    question: {
      q: "Iron objects rust faster near the sea. Why?",
      options: ["Salty, moist sea air speeds up rusting", "Sea air has no oxygen at all"],
      ans: 0,
      correctMsg: "Correct! Sea air is salty and humid, and salt plus moisture make iron rust much faster.",
      incorrectMsg: "Not quite — sea air is full of oxygen. It is the salt and moisture that speed up rusting. Try again!",
    },
    conclusion: "Iron rusts only when both air (oxygen) and moisture are present — nails in water, salt water and damp air all rust. Shutting out air (oil seal) or moisture (drying agent, paint) prevents rusting. This is why we oil, grease, paint or galvanise iron.",
  },

  /* ───────── Class 8 · Chemistry — combustion ───────── */
  combustion: {
    id: "combustion",
    title: "Combustible & Non-Combustible Materials",
    cls: "Class 8", subject: "Chemistry",
    chapter: "Ch 6 · Combustion and Flame",
    icon: "spark", accent: "#ea580c", mode: "burn",
    aim: "To test which materials catch fire and burn (combustible) and which do not (non-combustible).",
    theory: "A substance that burns in air, producing heat and usually light, is combustible. The lowest temperature at which it catches fire is its ignition temperature. Materials that do not burn are non-combustible.",
    materials: ["Burning matchstick / candle", "Paper", "Dry wood", "Kerosene", "Iron nail", "Glass", "Stone"],
    testVerb: "Bring a flame near it",
    categories: [
      { key: "combustible", label: "Combustible", color: "#ea580c", desc: "Catches fire and burns" },
      { key: "noncombustible", label: "Non-combustible", color: "#475569", desc: "Does not burn" },
    ],
    items: [
      { id: "paper", name: "Paper", shape: "sheet", color: "#ffffff", category: "combustible", fact: "Paper has a low ignition temperature — the flame makes it catch fire at once. Combustible." },
      { id: "wood", name: "Dry Wood", shape: "block", color: "#92623a", category: "combustible", fact: "Dry wood burns steadily, giving heat and light — a combustible material." },
      { id: "kerosene", name: "Kerosene", shape: "liquid", color: "#fde68a", category: "combustible", fact: "Kerosene is a highly combustible fuel — its vapour catches fire very easily, so it must be handled with care." },
      { id: "ironnail", name: "Iron Nail", shape: "nail", color: "#c3c7cd", category: "noncombustible", fact: "The flame may make it hot, but the iron nail does not catch fire — it is non-combustible." },
      { id: "glass", name: "Glass", shape: "slab", color: "#dbeafe", category: "noncombustible", fact: "Glass does not burn in a flame — it is non-combustible (it may only soften if very hot)." },
      { id: "stone", name: "Stone", shape: "lump", color: "#9ca3af", category: "noncombustible", fact: "A stone will not catch fire at all — it is non-combustible." },
    ],
    question: {
      q: "Why is a matchstick made of wood and tipped with chemicals, not made of iron?",
      options: ["Wood and the tip chemicals are combustible; iron is not", "Iron is too expensive for matchsticks"],
      ans: 0,
      correctMsg: "Correct! A match must catch fire easily, so it is made of combustible wood with a low-ignition tip — iron simply would not burn.",
      incorrectMsg: "Think about burning, not cost — iron does not catch fire, so it could never work as a match. Try again!",
    },
    conclusion: "Paper, wood and kerosene catch fire and burn — they are combustible. Iron, glass and stone do not burn — they are non-combustible. Knowing this helps us choose safe materials and store fuels carefully.",
  },

  /* ───────── Class 8 · Physics — regular vs diffused reflection ───────── */
  reflection: {
    id: "reflection",
    title: "Regular & Diffused Reflection",
    cls: "Class 8", subject: "Physics",
    chapter: "Ch 16 · Light",
    icon: "eye", accent: "#0284c7", mode: "reflect",
    aim: "To see how different surfaces reflect light — keeping the rays together (regular) or scattering them (diffused).",
    theory: "When parallel rays of light fall on a smooth, polished surface they are reflected parallel and we get a clear image — this is regular reflection. On a rough surface the rays are reflected in many different directions — this is diffused (irregular) reflection. In both, the laws of reflection still hold at each point.",
    materials: ["Light source (parallel rays)", "Plane mirror", "Polished steel plate", "Still water surface", "Painted wall", "Sheet of paper", "Wooden table top"],
    testVerb: "Shine parallel rays on it",
    categories: [
      { key: "regular", label: "Regular", color: "#0284c7", desc: "Smooth surface — rays stay parallel" },
      { key: "diffused", label: "Diffused", color: "#d97706", desc: "Rough surface — rays scatter" },
    ],
    items: [
      { id: "mirror", name: "Plane Mirror", shape: "panel", color: "#e2e8f0", category: "regular", fact: "The polished mirror reflects the parallel rays parallel — regular reflection. That is why a mirror forms a clear image." },
      { id: "steel", name: "Polished Steel Plate", shape: "panel", color: "#cbd5e1", category: "regular", fact: "A smooth, shiny steel surface also keeps the rays together — regular reflection, almost like a mirror." },
      { id: "water", name: "Still Water Surface", shape: "slab", color: "#bfe3f0", category: "regular", fact: "Calm, still water is smooth enough to reflect rays regularly — that is why it shows reflections of the sky and trees." },
      { id: "wall", name: "Painted Wall", shape: "block", color: "#e5e7eb", category: "diffused", fact: "The wall looks smooth but is rough up close, so it scatters the rays in all directions — diffused reflection. No image forms." },
      { id: "paper", name: "Sheet of Paper", shape: "sheet", color: "#ffffff", category: "diffused", fact: "Paper scatters light in every direction, which is why we can read it from any angle but never see our face in it — diffused reflection." },
      { id: "wood", name: "Wooden Table Top", shape: "block", color: "#92623a", category: "diffused", fact: "The wood's rough surface reflects rays every which way — diffused reflection, so there is no clear image." },
    ],
    question: {
      q: "Why can you see your face in a mirror but not in a sheet of paper?",
      options: ["The mirror is smooth (regular reflection); paper is rough (diffused)", "Paper does not reflect any light at all"],
      ans: 0,
      correctMsg: "Correct! A smooth mirror reflects rays in an orderly, parallel way (regular reflection), forming an image; rough paper scatters them (diffused), so no image forms.",
      incorrectMsg: "Paper does reflect light — that is how you see it. The difference is the smooth mirror reflects regularly while rough paper scatters the light. Try again!",
    },
    conclusion: "Smooth surfaces — a mirror, polished steel and still water — reflect parallel rays parallel (regular reflection) and form clear images. Rough surfaces — a wall, paper and wood — scatter the rays (diffused reflection), so no image forms, though the laws of reflection hold at every point.",
  },

  /* ───────── Class 8 · Physics — friction ───────── */
  friction: {
    id: "friction",
    title: "Friction: Rough & Smooth Surfaces",
    cls: "Class 8", subject: "Physics",
    chapter: "Ch 12 · Friction",
    icon: "target", accent: "#0f766e", mode: "slide",
    aim: "To compare how easily a block slides over different surfaces and classify each as having more or less friction.",
    theory: "Friction is the force that opposes motion between two surfaces in contact. Rough surfaces interlock more and produce more friction, so a sliding object stops quickly. Smooth or oily surfaces produce less friction, so the object glides far.",
    materials: ["Wooden block", "Sandpaper", "Carpet", "Gravel road", "Glass sheet", "Ice slab", "Oiled floor"],
    testVerb: "Push the block across it",
    categories: [
      { key: "high", label: "More Friction", color: "#b45309", desc: "Rough — block stops quickly" },
      { key: "low", label: "Less Friction", color: "#0284c7", desc: "Smooth — block glides far" },
    ],
    items: [
      { id: "sandpaper", name: "Sandpaper", shape: "panel", color: "#a16207", category: "high", fact: "The gritty surface grips the block strongly — lots of friction, so it barely moves. More friction." },
      { id: "carpet", name: "Carpet", shape: "block", color: "#7c3aed", category: "high", fact: "The fibres of the carpet drag on the block — high friction, the block stops almost at once. More friction." },
      { id: "gravel", name: "Gravel Road", shape: "block", color: "#94a3b8", category: "high", fact: "The rough, uneven gravel produces a lot of friction, so the block can hardly slide. More friction." },
      { id: "glass", name: "Glass Sheet", shape: "slab", color: "#dbeafe", category: "low", fact: "The smooth glass lets the block glide a long way — very little friction. Less friction." },
      { id: "ice", name: "Ice Slab", shape: "crystal", color: "#bfdbfe", category: "low", fact: "Ice is extremely smooth and slippery, so the block slides far with hardly any friction. Less friction." },
      { id: "oiled", name: "Oiled Floor", shape: "panel", color: "#cbd5e1", category: "low", fact: "A film of oil keeps the surfaces apart, so the block slides easily — that is why oil is used as a lubricant. Less friction." },
    ],
    question: {
      q: "Why do we slip on a wet or oily floor?",
      options: ["Water or oil reduces the friction, so our feet slide", "Water increases the friction between feet and floor"],
      ans: 0,
      correctMsg: "Correct! Water or oil lowers the friction between our feet and the floor, so we slip. That is also why floors are wiped dry.",
      incorrectMsg: "It is the opposite — water and oil reduce friction, which is exactly why the floor becomes slippery. Try again!",
    },
    conclusion: "Rough surfaces — sandpaper, carpet and gravel — produce more friction and stop the block quickly. Smooth or oily surfaces — glass, ice and an oiled floor — produce less friction and let it glide far. Friction can be increased (treads, grooves) or reduced (polishing, lubricants) as needed.",
  },

  /* ───────── Class 9 · Chemistry — solutions, suspensions & colloids ───────── */
  solutions: {
    id: "solutions",
    title: "Solutions, Suspensions & Colloids",
    cls: "Class 9", subject: "Chemistry",
    chapter: "Ch 2 · Is Matter Around Us Pure",
    icon: "beaker", accent: "#0284c7", mode: "tyndall",
    aim: "To shine a beam of light through different mixtures and classify each as a true solution, a colloid or a suspension.",
    theory: "In a true solution the particles are so small that light passes straight through and the beam is invisible. In a colloid the particles are bigger and scatter the light, so the beam's path is visible — the Tyndall effect. In a suspension the particles are large, make the liquid cloudy and slowly settle down.",
    materials: ["Beaker & light source", "Salt", "Copper sulphate", "Milk", "Starch solution", "Muddy water", "Chalk powder"],
    testVerb: "Shine a beam through it",
    categories: [
      { key: "solution", label: "Solution", color: "#0284c7", desc: "Clear — light passes straight through" },
      { key: "colloid", label: "Colloid", color: "#d97706", desc: "Scatters light (Tyndall effect)" },
      { key: "suspension", label: "Suspension", color: "#b45309", desc: "Cloudy — particles settle" },
    ],
    items: [
      { id: "saltwater", name: "Salt in Water", shape: "cup", color: "#eaf3f6", category: "solution", fact: "The salt dissolves completely; the liquid is clear and the light beam passes straight through unseen — a true solution." },
      { id: "coppersulphate", name: "Copper Sulphate Solution", shape: "cup", color: "#60a5fa", category: "solution", fact: "Even though it is blue, it is perfectly clear and does not scatter light — a true solution." },
      { id: "milk", name: "Milk", shape: "cup", color: "#fdfdfb", category: "colloid", fact: "Milk's tiny fat droplets scatter the beam, lighting up its path — the Tyndall effect. Milk is a colloid." },
      { id: "starch", name: "Starch Solution", shape: "cup", color: "#eef2e9", category: "colloid", fact: "Starch particles scatter the light so the beam is visible — a colloid, just like milk." },
      { id: "muddy", name: "Muddy Water", shape: "cup", color: "#a98c66", category: "suspension", fact: "The mud particles are large, make the water cloudy and slowly sink to the bottom — a suspension." },
      { id: "chalk", name: "Chalk in Water", shape: "cup", color: "#e2e8f0", category: "suspension", fact: "Chalk does not dissolve; it turns the water cloudy and settles down — a suspension." },
    ],
    question: {
      q: "A beam of light is clearly visible passing through a glass of milk but not through salt water. Why?",
      options: ["Milk is a colloid whose particles scatter light (Tyndall effect)", "Salt water has no particles in it at all"],
      ans: 0,
      correctMsg: "Correct! Milk's colloidal particles are large enough to scatter the light, making the beam visible — the Tyndall effect. A true solution does not scatter light.",
      incorrectMsg: "Salt water is full of particles — they are just too small to scatter light. Milk's bigger colloidal particles do scatter it. Try again!",
    },
    conclusion: "Salt and copper sulphate form clear true solutions (no Tyndall effect). Milk and starch solution are colloids that scatter light (the Tyndall effect). Muddy water and chalk in water are suspensions — cloudy mixtures whose particles settle on standing.",
  },

  /* ───────── Class 9 · Chemistry — states of matter ───────── */
  "states-of-matter": {
    id: "states-of-matter",
    title: "States of Matter",
    cls: "Class 9", subject: "Chemistry",
    chapter: "Ch 1 · Matter in Our Surroundings",
    icon: "atom", accent: "#2563eb", mode: "states",
    aim: "To examine the particle arrangement of everyday samples and classify each as a solid, a liquid or a gas.",
    theory: "In a solid the particles are tightly packed in a fixed arrangement and only vibrate, so a solid keeps its shape and volume. In a liquid the particles are loosely packed and can slip past each other, so a liquid flows and takes the container's shape but keeps its volume. In a gas the particles are far apart and move freely and fast, so a gas fills all the space available.",
    materials: ["Particle viewer box", "Ice", "Wooden block", "Water", "Cooking oil", "Oxygen", "Steam"],
    testVerb: "View the particles",
    categories: [
      { key: "solid", label: "Solid", color: "#2563eb", desc: "Fixed shape & volume — packed particles" },
      { key: "liquid", label: "Liquid", color: "#0d9488", desc: "Fixed volume, flows — loose particles" },
      { key: "gas", label: "Gas", color: "#ea580c", desc: "Fills space — free, fast particles" },
    ],
    items: [
      { id: "ice", name: "Ice", shape: "crystal", color: "#bfdbfe", category: "solid", fact: "The particles sit in a tight, ordered lattice and only vibrate — ice has a fixed shape and volume. A solid." },
      { id: "wood", name: "Wooden Block", shape: "block", color: "#92623a", category: "solid", fact: "Tightly packed particles hold a fixed shape — wood is a solid." },
      { id: "water", name: "Water", shape: "cup", color: "#bfe3f0", category: "liquid", fact: "The particles slip past one another, so water flows and takes the shape of its container while keeping its volume — a liquid." },
      { id: "oil", name: "Cooking Oil", shape: "liquid", color: "#f4d03f", category: "liquid", fact: "Oil flows and takes the container's shape — its particles are loosely packed. A liquid." },
      { id: "oxygen", name: "Oxygen Gas", shape: "orb", color: "#a7f3d0", category: "gas", fact: "The particles are far apart and zoom around freely, filling all the space — oxygen is a gas." },
      { id: "steam", name: "Steam (Water Vapour)", shape: "orb", color: "#e2e8f0", category: "gas", fact: "On boiling, water's particles spread far apart and move fast, filling the room — steam is a gas." },
    ],
    question: {
      q: "Why does a gas fill any container completely, while a liquid does not?",
      options: ["A gas's particles are far apart and move freely in all directions", "A gas has no particles, so it has nothing to hold it down"],
      ans: 0,
      correctMsg: "Correct! In a gas the particles are far apart with lots of freedom to move, so they spread out and fill the whole container.",
      incorrectMsg: "A gas certainly has particles — they are just far apart and move freely, which is why a gas fills its container. Try again!",
    },
    conclusion: "Ice and wood are solids (packed particles, fixed shape). Water and oil are liquids (loose particles, they flow but keep their volume). Oxygen and steam are gases (free, fast particles that fill the space). The state depends on how the particles are arranged and move.",
  },

  /* ───────── Class 9 · Chemistry — elements, compounds & mixtures ───────── */
  "elements-compounds": {
    id: "elements-compounds",
    title: "Elements, Compounds & Mixtures",
    cls: "Class 9", subject: "Chemistry",
    chapter: "Ch 2 · Is Matter Around Us Pure",
    icon: "flask", accent: "#7c3aed", mode: "inspect",
    aim: "To classify pure substances and mixtures as elements, compounds or mixtures.",
    theory: "An element is made of only one kind of atom and cannot be broken into simpler substances. A compound is made of two or more elements chemically combined in a fixed ratio, with new properties. A mixture contains two or more substances simply mixed in any ratio and can be separated physically.",
    materials: ["Magnifier", "Gold", "Oxygen", "Water", "Common salt", "Air", "Brass"],
    testVerb: "Examine the substance",
    categories: [
      { key: "element", label: "Element", color: "#0d9488", desc: "One kind of atom only" },
      { key: "compound", label: "Compound", color: "#7c3aed", desc: "Elements chemically combined, fixed ratio" },
      { key: "mixture", label: "Mixture", color: "#d97706", desc: "Substances simply mixed, any ratio" },
    ],
    items: [
      { id: "gold", name: "Gold", shape: "lump", color: "#fbbf24", category: "element", fact: "Gold is made of only gold atoms and cannot be broken into anything simpler — it is an element." },
      { id: "oxygen", name: "Oxygen", shape: "orb", color: "#a7f3d0", category: "element", fact: "Oxygen gas is made of a single kind of atom — it is an element." },
      { id: "water", name: "Water", shape: "cup", color: "#bfe3f0", category: "compound", fact: "Water is hydrogen and oxygen chemically combined in a fixed 2:1 ratio, with new properties — a compound." },
      { id: "salt", name: "Common Salt", shape: "crystal", color: "#eef2f7", category: "compound", fact: "Common salt is sodium and chlorine chemically combined in a fixed ratio — a compound." },
      { id: "air", name: "Air", shape: "orb", color: "#dbeafe", category: "mixture", fact: "Air is several gases simply mixed in no fixed ratio and can be separated physically — a mixture." },
      { id: "brass", name: "Brass", shape: "lump", color: "#d4a017", category: "mixture", fact: "Brass is copper and zinc mixed together (an alloy) in no fixed ratio — a mixture." },
    ],
    question: {
      q: "Water can be split into hydrogen and oxygen, and always has them in a fixed 2:1 ratio. What is water?",
      options: ["A compound — elements chemically combined in a fixed ratio", "A mixture — gases simply mixed together"],
      ans: 0,
      correctMsg: "Correct! A fixed ratio and new properties from chemically combined elements make water a compound, not a mixture.",
      incorrectMsg: "In a mixture the ratio can vary and components keep their own properties. Water has a fixed ratio and new properties — it is a compound. Try again!",
    },
    conclusion: "Gold and oxygen are elements (one kind of atom). Water and common salt are compounds (elements chemically combined in fixed ratios). Air and brass are mixtures (substances simply mixed, separable physically).",
  },

  /* ───────── Class 9 · Physics — Newton's laws of motion ───────── */
  force: {
    id: "force",
    title: "Newton's Three Laws of Motion",
    cls: "Class 9", subject: "Physics",
    chapter: "Ch 9 · Force & Laws of Motion",
    icon: "target", accent: "#0ea5e9", mode: "inspect",
    aim: "To examine everyday situations and identify which of Newton's three laws of motion each one shows.",
    theory: "Newton's first law (inertia): an object stays at rest or in uniform motion unless a net force acts on it. Second law: the force on an object equals its mass times its acceleration (F = ma) — more force or less mass gives more acceleration. Third law: every action has an equal and opposite reaction.",
    materials: ["Situation cards", "Toy car & track", "Ball", "Model rocket"],
    testVerb: "Study the situation",
    categories: [
      { key: "first", label: "First Law", color: "#0d9488", desc: "Inertia — rest or uniform motion" },
      { key: "second", label: "Second Law", color: "#0284c7", desc: "F = ma" },
      { key: "third", label: "Third Law", color: "#d97706", desc: "Action = reaction" },
    ],
    items: [
      { id: "seatbelt", name: "Lurch When a Bus Stops", shape: "car", color: "#dc2626", category: "first", fact: "When the bus stops suddenly your body keeps moving forward — that tendency to keep moving is inertia, Newton's first law." },
      { id: "book", name: "Book Resting on a Table", shape: "block", color: "#92623a", category: "first", fact: "The book stays at rest until a force moves it — an object keeps its state of rest by inertia. The first law." },
      { id: "heavycart", name: "Pushing a Loaded Cart", shape: "block", color: "#64748b", category: "second", fact: "A heavily loaded cart needs much more force to get the same acceleration as an empty one — F = ma, the second law." },
      { id: "kickball", name: "Kicking a Ball Harder", shape: "ball", color: "#f59e0b", category: "second", fact: "Kick the same ball harder and it accelerates more — acceleration depends on the force applied. F = ma, the second law." },
      { id: "rocket", name: "A Rocket Lifting Off", shape: "top", color: "#cbd5e1", category: "third", fact: "The rocket pushes hot gases downward and the gases push the rocket upward — action and reaction, the third law." },
      { id: "swimmer", name: "A Swimmer Pushing Water", shape: "strip", color: "#0284c7", category: "third", fact: "The swimmer pushes the water backward and the water pushes the swimmer forward — every action has an equal, opposite reaction. The third law." },
    ],
    question: {
      q: "A rocket rises by pushing gases downward. Which law of motion is this?",
      options: ["Third law — action and reaction are equal and opposite", "First law — the rocket has inertia"],
      ans: 0,
      correctMsg: "Correct! The downward push on the gases (action) produces an equal upward push on the rocket (reaction) — Newton's third law.",
      incorrectMsg: "Inertia is about staying at rest or in uniform motion. A rocket rising from the push-back of gases is action–reaction — the third law. Try again!",
    },
    conclusion: "The lurch when a bus stops and a book staying at rest show inertia (first law). A loaded cart and a harder kick show that force = mass × acceleration (second law). A lifting rocket and a swimming stroke show action and reaction (third law).",
  },

  /* ───────── Class 9 · Physics — kinetic & potential energy ───────── */
  energy: {
    id: "energy",
    title: "Kinetic & Potential Energy",
    cls: "Class 9", subject: "Physics",
    chapter: "Ch 11 · Work and Energy",
    icon: "bolt", accent: "#dc2626", mode: "inspect",
    aim: "To examine everyday situations and classify the energy as kinetic (energy of motion) or potential (stored energy).",
    theory: "Kinetic energy is the energy a body has because of its motion — the faster or heavier it moves, the more it has. Potential energy is stored energy — gravitational potential energy from height, or elastic potential energy from being stretched or compressed.",
    materials: ["Situation cards", "Toy car", "Bow", "Spring", "Model dam"],
    testVerb: "Study the situation",
    categories: [
      { key: "kinetic", label: "Kinetic", color: "#0284c7", desc: "Energy of motion" },
      { key: "potential", label: "Potential", color: "#d97706", desc: "Stored energy (height or stretch)" },
    ],
    items: [
      { id: "movingcar", name: "A Moving Car", shape: "car", color: "#dc2626", category: "kinetic", fact: "A moving car has kinetic energy — the energy of motion. The faster it goes, the more it has." },
      { id: "flowingwater", name: "Flowing River Water", shape: "cup", color: "#3b82f6", category: "kinetic", fact: "Flowing water is in motion, so it carries kinetic energy — enough to turn a water wheel or turbine." },
      { id: "bullet", name: "A Speeding Bullet", shape: "strip", color: "#94a3b8", category: "kinetic", fact: "A fast bullet, though tiny, carries large kinetic energy because of its high speed — energy of motion." },
      { id: "stretchedbow", name: "A Stretched Bow", shape: "ribbon", color: "#a16207", category: "potential", fact: "A stretched bow stores elastic potential energy, which is released into the arrow when let go." },
      { id: "damwater", name: "Water Stored in a Dam", shape: "cup", color: "#0ea5e9", category: "potential", fact: "Water held high in a dam has gravitational potential energy because of its height — released as it falls." },
      { id: "raisedhammer", name: "A Raised Hammer", shape: "lump", color: "#475569", category: "potential", fact: "A hammer held up high has gravitational potential energy, ready to do work as it comes down." },
    ],
    question: {
      q: "Water stored high up in a dam has which kind of energy?",
      options: ["Gravitational potential energy — stored because of its height", "Kinetic energy — because it is moving"],
      ans: 0,
      correctMsg: "Correct! Still water held high has gravitational potential energy due to its height; it turns into kinetic energy only as it falls.",
      incorrectMsg: "The stored water is not moving yet — it has potential energy because of its height. It becomes kinetic only as it falls. Try again!",
    },
    conclusion: "A moving car, flowing water and a speeding bullet have kinetic energy (energy of motion). A stretched bow, dammed water and a raised hammer have potential energy (stored by stretch or height). Energy changes from one form to the other — e.g. dam water's potential energy becomes kinetic as it falls.",
  },
};
