/* ── CBSE-format practical record generator ──
   Turns a student's completed labs into a print-ready Science Practical File
   (PDF) — the artifact schools need for CBSE internal/practical assessment.
   Pure client-side (jsPDF) → ₹0 marginal cost. Works for an individual student
   and (via the teacher dashboard) per-student across a whole class. */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { GEN_LABS } from "./genlabdata.js";
import { CATALOG } from "./data.js";

const INK = [15, 23, 42];
const SUB = [100, 116, 139];
const GREEN = [13, 148, 136];
const LINE = [203, 213, 225];

const specFor = (c) => GEN_LABS[c.experimentId || c.id] || null;
const catFor = (c) => CATALOG.find((e) => e.id === (c.experimentId || c.id)) || {};
const labelOf = (spec, key) => {
  const cc = spec && (spec.categories || []).find((c) => c.key === key);
  return cc ? cc.label : key || "—";
};

function header(doc, student) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 16, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("LabSpark AI", 14, 10.5);
  doc.setFont("helvetica", "normal").setFontSize(8);
  doc.setTextColor(186, 230, 253);
  doc.text("Science Practical Record", W - 14, 10.5, { align: "right" });
}

function footer(doc) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const n = doc.internal.getNumberOfPages();
  doc.setFont("helvetica", "normal").setFontSize(7.5).setTextColor(...SUB);
  doc.text("Generated by LabSpark AI — virtual science labs aligned to the NCERT/CBSE practical syllabus.", 14, H - 7);
  doc.text(`Page ${n}`, W - 14, H - 7, { align: "right" });
}

function coverPage(doc, student, count) {
  const W = doc.internal.pageSize.getWidth();
  header(doc, student);
  doc.setFont("helvetica", "bold").setFontSize(22).setTextColor(...INK);
  doc.text("SCIENCE PRACTICAL FILE", W / 2, 56, { align: "center" });
  doc.setDrawColor(...GREEN).setLineWidth(0.8);
  doc.line(W / 2 - 42, 61, W / 2 + 42, 61);
  doc.setFont("helvetica", "normal").setFontSize(11).setTextColor(...SUB);
  doc.text("Virtual Laboratory Record · NCERT / CBSE aligned", W / 2, 69, { align: "center" });

  const rows = [
    ["Student Name", student.name || "—"],
    ["School", student.school || "—"],
    ["Class & Section", `${student.klass || "—"}${student.section ? "  ·  Section " + student.section : ""}`],
    ["Roll Number", student.rollNo || "—"],
    ["Experiments Recorded", String(count)],
    ["Generated On", new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })],
  ];
  autoTable(doc, {
    startY: 86,
    margin: { left: 32, right: 32 },
    theme: "grid",
    styles: { fontSize: 11, cellPadding: 4, lineColor: LINE, textColor: INK },
    columnStyles: { 0: { fontStyle: "bold", fillColor: [248, 250, 252], cellWidth: 60, textColor: SUB }, 1: { fontStyle: "bold" } },
    body: rows,
  });

  doc.setFont("helvetica", "italic").setFontSize(9).setTextColor(...SUB);
  doc.text(
    "Disclaimer: This is a LabSpark-issued practical record generated from virtual experiments. It is aligned to the\nNCERT/CBSE practical syllabus but is not an official NCERT/CBSE document.",
    W / 2, 250, { align: "center" }
  );
  footer(doc);
}

function labSection(doc, c, idx) {
  const spec = specFor(c);
  const cat = catFor(c);
  const W = doc.internal.pageSize.getWidth();
  doc.addPage();
  header(doc, null);

  const title = c.name || (spec && spec.title) || cat.name || "Experiment";
  const chapter = (spec && spec.chapter) || cat.chapter || "";
  let y = 26;

  doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(...GREEN);
  doc.text(`EXPERIMENT ${idx}`, 14, y);
  doc.setFontSize(15).setTextColor(...INK);
  y += 7;
  doc.text(doc.splitTextToSize(title, W - 28), 14, y);
  y += 7;
  if (chapter) {
    doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(...SUB);
    doc.text(chapter, 14, y);
    y += 6;
  }

  const para = (label, text) => {
    if (!text) return;
    doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(...GREEN);
    doc.text(label, 14, y); y += 5;
    doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(...INK);
    const lines = doc.splitTextToSize(text, W - 28);
    doc.text(lines, 14, y);
    y += lines.length * 4.6 + 4;
  };

  para("AIM", c.aim || (spec && spec.aim));
  if (spec && spec.materials) para("MATERIALS / APPARATUS", spec.materials.join(", ") + ".");
  para("THEORY / PROCEDURE", spec && spec.theory);

  // Observation table — prefer the student's own verdicts, else the model answers.
  const obs = Array.isArray(c.observations) && c.observations.length ? c.observations : null;
  if (obs || (spec && spec.items)) {
    doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(...GREEN);
    doc.text("OBSERVATION TABLE", 14, y); y += 2;
    // Add a Hypothesis column when the student recorded predictions (Socratic labs).
    const hasPred = obs && obs.some((o) => o.prediction);
    const head = hasPred
      ? [["#", "Sample / Item", "Predicted", "Your Answer", "Correct", "Remark"]]
      : [["#", "Sample / Item", "Your Answer", "Correct", "Remark"]];
    const body = obs
      ? obs.map((o, i) => hasPred
          ? [i + 1, o.name, o.prediction ? labelOf(spec, o.prediction) : "—", labelOf(spec, o.studentVerdict), labelOf(spec, o.correct), o.studentVerdict === o.correct ? "Correct" : "Review"]
          : [i + 1, o.name, labelOf(spec, o.studentVerdict), labelOf(spec, o.correct), o.studentVerdict === o.correct ? "Correct" : "Review"])
      : spec.items.map((it, i) => [i + 1, it.name, "—", labelOf(spec, it.category), ""]);
    autoTable(doc, {
      startY: y + 2,
      margin: { left: 14, right: 14 },
      theme: "grid",
      headStyles: { fillColor: INK, textColor: [255, 255, 255], fontSize: 8.5 },
      styles: { fontSize: 9, cellPadding: 2.5, lineColor: LINE, textColor: INK },
      columnStyles: { 0: { cellWidth: 10 } },
      head,
      body,
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  para("RESULT / CONCLUSION", c.conclusion || (spec && spec.conclusion));

  if (spec && spec.question) {
    doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(...GREEN);
    doc.text("VIVA VOCE", 14, y); y += 5;
    doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(...INK);
    const q = doc.splitTextToSize("Q. " + spec.question.q, W - 28);
    doc.text(q, 14, y); y += q.length * 4.6 + 2;
    const ans = doc.splitTextToSize("A. " + spec.question.options[spec.question.ans], W - 28);
    doc.setFont("helvetica", "bold").setTextColor(...GREEN);
    doc.text(ans, 14, y); y += ans.length * 4.6 + 4;
  }

  // score + date strip
  doc.setDrawColor(...LINE).setLineWidth(0.3);
  doc.line(14, y, W - 14, y); y += 6;
  doc.setFont("helvetica", "bold").setFontSize(10).setTextColor(...INK);
  if (typeof c.correct === "number" && typeof c.total === "number") {
    doc.text(`Score: ${c.correct} / ${c.total}`, 14, y);
  }
  // Internal-assessment marks (teacher-approved mark wins over the AI draft).
  if (typeof c.teacherMark === "number" || typeof c.aiMark === "number") {
    const hasT = typeof c.teacherMark === "number";
    const m = hasT ? c.teacherMark : c.aiMark;
    const max = c.aiMarkMax || 5;
    doc.text(`Marks: ${m} / ${max}`, W / 2, y, { align: "center" });
    doc.setFont("helvetica", "normal").setFontSize(7.5).setTextColor(...SUB);
    doc.text(hasT && c.marksApproved ? "teacher-assessed" : "AI draft — pending teacher approval", W / 2, y + 3.6, { align: "center" });
    doc.setFont("helvetica", "bold").setFontSize(10).setTextColor(...INK);
  }
  doc.setFont("helvetica", "normal").setTextColor(...SUB);
  if (c.date) doc.text(`Date: ${c.date}`, W - 14, y, { align: "right" });

  footer(doc);
}

/* Build a multi-lab practical file for one student. */
export function buildPracticalFile(student, completions) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const list = (completions || []).filter(Boolean);
  coverPage(doc, student, list.length);
  list.forEach((c, i) => labSection(doc, c, i + 1));
  return doc;
}

const safe = (s) => (s || "student").replace(/[^a-z0-9]+/gi, "_").slice(0, 40);

/* Download the full practical file (all completed labs) for one student. */
export function downloadPracticalFile(student, completions) {
  const doc = buildPracticalFile(student, completions);
  doc.save(`Practical_File_${safe(student.name)}.pdf`);
}

/* Download a single lab's record (used from the report screen). */
export function downloadLabRecord(student, completion) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  coverPage(doc, student, 1);
  labSection(doc, completion, 1);
  doc.save(`Practical_${safe(student.name)}_${safe(completion.name || completion.id)}.pdf`);
}
